sudo: required
services:
- docker
install:
- bundle install
script:
- kitchen test
notifications:
  email: false
  slack:
    secure: YUmWXPAfwKenZyHnE3LGm47+XievMR8Ib++xPFeK/VzvDJliwa0ssldt2wOT9uZEWRaUGA8TtL2TKrkEAcqrU78mDtTIY2hcdJDVIRqQg9Ktr5GghSa9Di6Hartnn0fEE7VM+pYe/6tALoFVZP6BTS7JNQyd4HLU4zcqHyWGae0hHrPQJVRd/L14o6689hNc8uz8Ahwf6Vo+trVgWr0GPb5NZlmCPrDJlxTrfdrtgDGXHbXU9aryIasvxmUXMdDGhUazfIw0GKBHi9g2Sjx0gichTEXOjpYCutIy/IeJeWhLNtnTrXh0j+16OGCSaaj0DSwZ/oQabrw412JTplwi40o1mEWZ3nL6vrV1gJ4L2UkOEq8RZYkH34Gy75OOufVempwR1TB2DAKOEekXA+tHlJgAaPrJf2GgPkm/Bq+P9EQ/i5yP86Y36fKaGROk83zDUiI2PbDbYbD2TdrGR9+DDwM3oQyy9/15u3XXvBZhE6IBLUETP6/I/ewSFEquAg9DezY1aTLF+DXl8MuQ360C++SolfDFYrP5JyNcDn4iRSvyyjSo1m8t55z+260mTYlayWVCJ4Tdv6hUEXX6BYyfoObommaZeDV/iKmInB9CYicesiLq5xX8ZTXtl6KzU5KXNVPQJvmd5NwL0q6y7T19OMBWs3Yp7HOMmCkEi0C9CT0=
    on_success: always
    on_failure: always